[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
cmds = ["cd backend && npm ci"]

[phases.build]
cmds = ["cd backend && npx prisma generate && npm run build"]

[start]
cmd = "cd backend && npm start"
